### ISSUE TITLE
Node versions incompatible with yarn

### ISSUE THREAD

**Issue by ShubhankarKG** [akashraj9828/gitstats#40]
**Is your feature request related to a problem? Please describe.**
This is a wonderful project currently. Kudos. As an enthusiast, I cloned the repo and ran `yarn start`. To my surprise I received a nice little message from yarn :
![Screenshot from 2020-05-12 09-34-22](https://user-images.githubusercontent.com/50791000/81637415-e4238f00-9433-11ea-80f5-949648f5e92a.png)

The commands with npm run just fine. As expected.

**Describe the solution you'd like**
Either change the installer to __npm__ or consider containerising the project to avoid any clashes in dependencies. 

**Describe alternatives you've considered**
The two above are what I thought seemed best.

**Additional context**
None currently. Let me know if I can help in this regard, or in any way that's beneficial.

**Comment by akashraj9828** [comment]
I was not aware of this issue! Thanks for reporting. 

No issues we can change the installer to `npm` that sound's a good solution right now.
I am not suggesting containerising because many folks are still unaware of Docker and they might have trouble with getting started.

Feel free to make an PR solving this issue.

**Comment by ShubhankarKG** [comment]
I'll file one as soon as I can. Thanks.

**Comment by ShubhankarKG** [comment]
Closing this since the issue has been resolved
